name: echoes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scikit-learn>=0.24.0
  - jupyter>=1.0.0
  - tqdm>=4.62.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - pip
  - pip:
    - wandb>=0.12.0  # for experiment tracking
    - mlflow>=2.0.0  # for experiment tracking
    - tensorboard>=2.0.0  # for experiment visualization
    - pre-commit
    - ruff
    - opencv-python-headless
    - tqdm
    - azure-storage-blob>=12.0.0  # for blob storage
    - pytest>=7.0.0  # for unit testing
    - pytest-cov>=4.0.0  # for test coverage
